import React from 'react';

const TestimonialsSection = ({ testimonials }) => {
  return (
    <section className="section section--testimonials">
      <div className="container">
        <div className="section-heading reveal">
          <p className="eyebrow">Guest impressions</p>
          <h2 className="section-title">A credible restaurant site should sound lived-in, not autogenerated.</h2>
        </div>

        <div className="testimonial-grid">
          {testimonials.map((testimonial) => (
            <article key={testimonial.name} className="testimonial-card reveal">
              <p className="testimonial-card__quote">&quot;{testimonial.quote}&quot;</p>
              <div className="testimonial-card__meta">
                <strong>{testimonial.name}</strong>
                <span>{testimonial.occasion}</span>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
};

export default TestimonialsSection;
